use_frameworks!

target 'com.awareframework.ios.sensor.battery_Example' do
  pod 'com.awareframework.ios.sensor.battery', :path => '../'

  target 'com.awareframework.ios.sensor.battery_Tests' do
    inherit! :search_paths

    
  end
end
