osx_image: xcode10.1
language: objective-c
cache: cocoapods
podfile: Example/Podfile
before_install:
- gem install cocoapods
- pod repo update
- pod install --project-directory=Example
script:
- set -o pipefail && xcodebuild test -enableCodeCoverage YES -workspace Example/com.awareframework.ios.sensor.battery.xcworkspace
  -scheme com.awareframework.ios.sensor.battery-Example -sdk iphonesimulator12.1 -destination
  OS=12.1,name="iPhone X" ONLY_ACTIVE_ARCH=NO CODE_SIGNING_REQUIRED=NO -allowProvisioningUpdates
  | XCPRETTY
deploy:
  provider: script
  script: "./scripts/release.sh"
  on:
    tags: true
after_success:
- echo 'success!'
env:
  global:
  - secure: SJH1zG0d5SDzCcG8R5vFID23fAul53gj+/9pntrakD9MKXKkr4Hx1XmeKmxbNGTfaNUDKbGqTJOKeILaihUJjEXt25Xvhvrcapd4P360/+Sg2Nl6z0Wn+3uOmrf8Ym/6NyryZ078LhZaGMJurZZqmv4xYUXDefHcqv67F7rzPo5hdcuCaxYq6fA6PflIebuEv5Yk7vLSa3500o9Tfv3CrFt4p/BCNe+x76YrN4HdBW9cBn0Nkq3f4QK67qQOE3FFsrt3FfIVtkB5szXalcFWOb/1f5T3ryLmB+S6NC5QHiNYcmKK3VSdIoWhTdgi6oGBm1JCr1wmbO0Z69SD7elbC3PDXXaS8EzLrb2zz0MqYPYKz+u5ATDb08KxVfKdCRJ4zRVcLPjRYZ8Sh7/S8c8WlotuphSUJZg72RGaEdIfPniwFpHLcUgoVbwhYYmHCf6njdsc4f6OPg6yGLmrA8PiCm4GcVR9jLc6FkLLOKBphbH+CEXHG1N6sCJuRbQ5QV/vJC2AjTeEmfWzgy9bCfSfRYRhWFP9eZh88+8eoXuGFfPr8pGXvxF8aI32/yhre8b4Ka+XbvZgBv0fvmMR++u9NdjOAzfUBDzDaBFSj4zCIeltaxmHqL9w0RglD9+lRYGRArhJlte7OeNCGMSBws50ygGU4zBwZWjYyCRGv9nehlk=
notifications:
  slack:
    secure: fWdBO9pEUGoufMT4OE+ilCvCG2Bu6bCyNabrzlwWLqSdQc20wpks5vGEJZZc2QmUBtTGQpDktEqJrhVOO2GH92tlFHJhCABWS9Qh2ptuzv6JNH2qNq00hHUrAmrTwD8kjQ0dUOE/2eiUxoItjHkuHUDgPmxtRftOSK39wGWbi2wMMAk45TAeEscvIHzQb2yB66+jylFISxIYZHBg1XxQIMSyZrF1izHudZSShJjPhga+fO8cBrFKu4x2etfLBfyT7g/kc1F3CIQG+9ohazeEBTYrAMFlKvoc+Trg2iIgASwrPh4OEJQaNwr3sG+F4KA801Ry7a6afpWEbFoWt8U+Um6HUg2XJHHf9FR05DLRKkWOM6Nvf05kcmq2P1TYgRw121ySwfimdYq+fhrfvWEk039BBxo0+AeTEvnOrO3TgYeEfTRC1PHAknsXYf95RqJJol9jD6/bNjZnn61sMIPNvbxIcIP7ThKXuT1B4zmS4A58FcbjcC0iBzIc76mnev0hTaUCLuse+a1AU3UlUCGSLWjhJ2Q/U2ZqDwgeEg0RMlrzQkZEaZ01zGPex7EArdjSTbvvB1naCPCMCrNHB0XLKcPpHGyJC1rmArBnTz5h/flmpOYrPLH2kB4sHp80z1XYGgyi5gYQQbPXH+lqOh31NekJoxFZn/sfcN24BRP1cIE=
